/******************************************************************************
 * This file was generated by langium-cli 1.1.0.
 * DO NOT EDIT MANUALLY!
 ******************************************************************************/

import { LangiumGeneratedServices, LangiumGeneratedSharedServices, LangiumSharedServices, LangiumServices, LanguageMetaData, Module } from 'langium';
import { LogikAstReflection } from './ast';
import { LogikGrammar } from './grammar';

export const LogikLanguageMetaData: LanguageMetaData = {
    languageId: 'logik',
    fileExtensions: ['.lgk'],
    caseInsensitive: false
};

export const LogikGeneratedSharedModule: Module<LangiumSharedServices, LangiumGeneratedSharedServices> = {
    AstReflection: () => new LogikAstReflection()
};

export const LogikGeneratedModule: Module<LangiumServices, LangiumGeneratedServices> = {
    Grammar: () => LogikGrammar(),
    LanguageMetaData: () => LogikLanguageMetaData,
    parser: {}
};
